<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="azkaban.executor.JdbcExecutorLoaderTest" tests="34" skipped="3" failures="0" errors="0" timestamp="2017-06-07T20:31:21" hostname="mars" time="0.03">
  <properties/>
  <testcase name="testMissingExecutorUpdate" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testExecutorActivation" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchActiveExecutors" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchAllExecutors" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testSingleExecutorFetchById" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testDuplicateAddExecutor" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchNoQueuedFlows" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testExecutorInactivation" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testAssignAndFetchExecutor" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testUnassignExecutorException" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testLargeUploadLog" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="testActiveReference" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchEmptyExecutorEvents" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchActiveFlowByExecId" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.001"/>
  <testcase name="testFetchRecentlyFinishedFlows" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testUpdateExecutionFlows" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testRemovingExecutor" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchExecutorByQueuedExecution" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchQueuedFlows" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchMissingExecutorByExecution" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testAssignExecutorInvalidExecutor" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testExecutorEvents" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchMissingExecutorId" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testAssignExecutorInvalidExecution" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.001"/>
  <testcase name="testUnassignExecutor" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testRemoveExecutionLogsByTime" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="testFetchEmptyRecentlyFinishedFlows" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testSmallUploadLog" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="testFetchEmptyExecutors" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testUploadExecutionFlows" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testFetchMissingExecutorHostPort" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.001"/>
  <testcase name="testFetchEmptyActiveExecutors" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testUploadExecutableNode" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <testcase name="testSingleExecutorFetchHostPort" classname="azkaban.executor.JdbcExecutorLoaderTest" time="0.0"/>
  <system-out><![CDATA[2017/06/07 21:31:21.476 +0100 ERROR [ExecutorManager] Failed to update ExecutorInfo for executor : localhost:12345 (id: 1)
java.util.concurrent.ExecutionException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at azkaban.executor.ExecutorManager.refreshExecutors(ExecutorManager.java:266)
	at azkaban.executor.ExecutorManager.access$1400(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1810)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:250)
	at azkaban.utils.RestfulApiClient.httpGet(RestfulApiClient.java:180)
	at azkaban.executor.ExecutorManager.callExecutorForJsonString(ExecutorManager.java:1160)
	at azkaban.executor.ExecutorManager.access$000(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$1.call(ExecutorManager.java:252)
	at azkaban.executor.ExecutorManager$1.call(ExecutorManager.java:249)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 19 more
2017/06/07 21:31:21.480 +0100 ERROR [ExecutorManager] Failed to update ExecutorInfo for executor : localhost:12346 (id: 2)
java.util.concurrent.ExecutionException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at azkaban.executor.ExecutorManager.refreshExecutors(ExecutorManager.java:266)
	at azkaban.executor.ExecutorManager.access$1400(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1810)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:250)
	at azkaban.utils.RestfulApiClient.httpGet(RestfulApiClient.java:180)
	at azkaban.executor.ExecutorManager.callExecutorForJsonString(ExecutorManager.java:1160)
	at azkaban.executor.ExecutorManager.access$000(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$1.call(ExecutorManager.java:252)
	at azkaban.executor.ExecutorManager$1.call(ExecutorManager.java:249)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 19 more
2017/06/07 21:31:21.483 +0100 INFO [ExecutorManager] Using dispatcher for execution id :-1
2017/06/07 21:31:21.562 +0100 ERROR [ExecutorManager] Rolling back executor assignment for execution id:-1
azkaban.executor.ExecutorManagerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1067)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1712)
	at azkaban.executor.ExecutorManager.access$1600(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1860)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1841)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:250)
	at azkaban.utils.RestfulApiClient.httpGet(RestfulApiClient.java:180)
	at azkaban.executor.ExecutorManager.callExecutorForJsonString(ExecutorManager.java:1160)
	at azkaban.executor.ExecutorManager.callExecutorForJsonObject(ExecutorManager.java:1132)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1120)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1064)
	... 5 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 20 more
2017/06/07 21:31:21.565 +0100 WARN [ExecutorManager] Executor localhost:12346 (id: 2) responded with exception for exec: -1
azkaban.executor.ExecutorManagerException: azkaban.executor.ExecutorManagerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1718)
	at azkaban.executor.ExecutorManager.access$1600(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1860)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1841)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
Caused by: azkaban.executor.ExecutorManagerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1067)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1712)
	... 4 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12346 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:250)
	at azkaban.utils.RestfulApiClient.httpGet(RestfulApiClient.java:180)
	at azkaban.executor.ExecutorManager.callExecutorForJsonString(ExecutorManager.java:1160)
	at azkaban.executor.ExecutorManager.callExecutorForJsonObject(ExecutorManager.java:1132)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1120)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1064)
	... 5 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 20 more
2017/06/07 21:31:21.566 +0100 INFO [ExecutorManager] Reached handleDispatchExceptionCase stage for exec -1 with error count 0
2017/06/07 21:31:21.566 +0100 INFO [ExecutorManager] Using dispatcher for execution id :-1
2017/06/07 21:31:21.610 +0100 ERROR [ExecutorManager] Rolling back executor assignment for execution id:-1
azkaban.executor.ExecutorManagerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1067)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1712)
	at azkaban.executor.ExecutorManager.access$1600(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1860)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.handleDispatchExceptionCase(ExecutorManager.java:1944)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1865)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1841)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:250)
	at azkaban.utils.RestfulApiClient.httpGet(RestfulApiClient.java:180)
	at azkaban.executor.ExecutorManager.callExecutorForJsonString(ExecutorManager.java:1160)
	at azkaban.executor.ExecutorManager.callExecutorForJsonObject(ExecutorManager.java:1132)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1120)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1064)
	... 7 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 22 more
2017/06/07 21:31:21.620 +0100 WARN [ExecutorManager] Executor localhost:12345 (id: 1) responded with exception for exec: -1
azkaban.executor.ExecutorManagerException: azkaban.executor.ExecutorManagerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1718)
	at azkaban.executor.ExecutorManager.access$1600(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1860)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.handleDispatchExceptionCase(ExecutorManager.java:1944)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1865)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1841)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
Caused by: azkaban.executor.ExecutorManagerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1067)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1712)
	... 6 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12345 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:250)
	at azkaban.utils.RestfulApiClient.httpGet(RestfulApiClient.java:180)
	at azkaban.executor.ExecutorManager.callExecutorForJsonString(ExecutorManager.java:1160)
	at azkaban.executor.ExecutorManager.callExecutorForJsonObject(ExecutorManager.java:1132)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1120)
	at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:1064)
	... 7 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 22 more
2017/06/07 21:31:21.622 +0100 INFO [ExecutorManager] Reached handleDispatchExceptionCase stage for exec -1 with error count 1
2017/06/07 21:31:21.622 +0100 ERROR [ExecutorManager] Failed to process queued flow
2017/06/07 21:31:21.622 +0100 ERROR [ExecutorManager] QueueProcessorThread Interrupted. Probably to shut down.
java.lang.NullPointerException
	at azkaban.executor.ExecutorManager.isFinished(ExecutorManager.java:1579)
	at azkaban.executor.ExecutorManager.finalizeFlows(ExecutorManager.java:1390)
	at azkaban.executor.ExecutorManager.access$1000(ExecutorManager.java:72)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.handleDispatchExceptionCase(ExecutorManager.java:1940)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1865)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.handleDispatchExceptionCase(ExecutorManager.java:1944)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1865)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1841)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1779)
]]></system-out>
  <system-err><![CDATA[java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at azkaban.executor.JdbcExecutorLoaderTest.setupDB(JdbcExecutorLoaderTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1129)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:358)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2489)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2526)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2311)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:347)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
	... 40 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:308)
	... 56 more
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
Skipping DB test because Db not setup.
]]></system-err>
</testsuite>
